twitter:
    consumer_key: YOUR_CONSUMER_KEY
    consumer_secret: YOUR_CONSUMER_SECRET
bot:
    watch_interval: 5
    message: |
        {{.User.Name | escape}} さんがスペースを開始しました
        {{.URL}}
healthcheck_server:
    enabled: false
    port: 18080
